services:
  - type: web
    name: portfolio-backend
    env: go
    buildCommand: go mod download && go build -o portfolio-server main.go
    startCommand: ./portfolio-server
    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: 8080
    healthCheckPath: /health
